import { ModelProviderCard } from '@/types/llm';

// Puter AI Gateway - Top 20 models
// Puter uses client-side puter.ai.chat() API, no API keys needed
// Full list: https://puter.com/ai-models
const Puter: ModelProviderCard = {
  chatModels: [
    {
      description: 'OpenAI GPT-4o — flagship multimodal model with vision, fast and intelligent',
      displayName: 'GPT-4o',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o',
      tokens: 128_000,
      vision: true,
    },
    {
      description: 'OpenAI GPT-4o Mini — compact and cost-effective, great for everyday tasks',
      displayName: 'GPT-4o Mini',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o-mini',
      maxOutput: 16_385,
      tokens: 128_000,
      vision: true,
    },
    {
      description: 'Anthropic Claude Sonnet 4 — excellent reasoning and coding capabilities',
      displayName: 'Claude Sonnet 4',
      enabled: true,
      functionCall: true,
      id: 'claude-sonnet-4-20250514',
      tokens: 200_000,
      vision: true,
    },
    {
      description: 'Anthropic Claude 3.5 Haiku — fast and lightweight for quick tasks',
      displayName: 'Claude 3.5 Haiku',
      enabled: true,
      id: 'claude-3-5-haiku-20241022',
      tokens: 200_000,
      vision: true,
    },
    {
      description: 'Google Gemini 2.0 Flash — fast multimodal model with great performance',
      displayName: 'Gemini 2.0 Flash',
      enabled: true,
      functionCall: true,
      id: 'gemini-2.0-flash',
      tokens: 1_048_576,
      vision: true,
    },
    {
      description: 'Google Gemini 2.5 Flash Preview — latest preview with thinking capabilities',
      displayName: 'Gemini 2.5 Flash Preview',
      enabled: true,
      functionCall: true,
      id: 'gemini-2.5-flash-preview-05-20',
      tokens: 1_048_576,
      vision: true,
    },
    {
      description: 'Meta Llama 4 Maverick — powerful open-source model from Meta',
      displayName: 'Llama 4 Maverick',
      enabled: true,
      id: 'meta-llama/llama-4-maverick',
      tokens: 128_000,
      vision: true,
    },
    {
      description: 'Meta Llama 4 Scout — efficient and versatile open model',
      displayName: 'Llama 4 Scout',
      enabled: true,
      id: 'meta-llama/llama-4-scout',
      tokens: 128_000,
      vision: true,
    },
    {
      description: 'DeepSeek Chat V3 — strong general purpose and coding model',
      displayName: 'DeepSeek Chat V3',
      enabled: true,
      id: 'deepseek/deepseek-chat-v3-0324',
      tokens: 128_000,
    },
    {
      description: 'DeepSeek R1 — advanced reasoning model with chain-of-thought',
      displayName: 'DeepSeek R1',
      enabled: true,
      id: 'deepseek/deepseek-r1',
      tokens: 128_000,
    },
    {
      description: 'Mistral Large — top-tier reasoning and multilingual model',
      displayName: 'Mistral Large',
      enabled: true,
      functionCall: true,
      id: 'mistralai/mistral-large-latest',
      tokens: 128_000,
    },
    {
      description: 'Mistral Small — fast and efficient for everyday tasks',
      displayName: 'Mistral Small',
      enabled: true,
      functionCall: true,
      id: 'mistralai/mistral-small-latest',
      tokens: 128_000,
    },
    {
      description: 'xAI Grok 3 Mini Beta — compact reasoning model from xAI',
      displayName: 'Grok 3 Mini Beta',
      enabled: true,
      id: 'x-ai/grok-3-mini-beta',
      tokens: 131_072,
    },
    {
      description: 'xAI Grok 3 Beta — powerful full-size model from xAI',
      displayName: 'Grok 3 Beta',
      enabled: true,
      id: 'x-ai/grok-3-beta',
      tokens: 131_072,
    },
    {
      description: 'Alibaba Qwen 2.5 72B Instruct — strong multilingual open model',
      displayName: 'Qwen 2.5 72B',
      enabled: true,
      id: 'qwen/qwen-2.5-72b-instruct',
      tokens: 128_000,
    },
    {
      description: 'Google Gemma 3 27B — efficient open model from Google',
      displayName: 'Gemma 3 27B',
      enabled: true,
      id: 'google/gemma-3-27b-it',
      tokens: 96_000,
      vision: true,
    },
    {
      description: 'Microsoft Phi-4 — compact yet powerful small language model',
      displayName: 'Phi-4',
      enabled: true,
      id: 'microsoft/phi-4',
      tokens: 16_384,
    },
    {
      description: 'NVIDIA Nemotron 70B — high-quality instruction-following model',
      displayName: 'Nemotron 70B',
      enabled: true,
      id: 'nvidia/llama-3.1-nemotron-70b-instruct',
      tokens: 128_000,
    },
    {
      description: 'Cohere Command R+ — enterprise-grade RAG and tool-use model',
      displayName: 'Command R+',
      enabled: true,
      functionCall: true,
      id: 'cohere/command-r-plus',
      tokens: 128_000,
    },
    {
      description: 'Perplexity Sonar Pro — search-augmented AI with real-time web access',
      displayName: 'Sonar Pro',
      enabled: true,
      id: 'perplexity/sonar-pro',
      tokens: 128_000,
    },
  ],
  checkModel: 'gpt-4o-mini',
  defaultShowBrowserRequest: true,
  enabled: true,
  id: 'puter',
  name: 'Puter',
  // No API key needed — Puter uses User-Pays model
  showApiKey: false,
};

export default Puter;
